### ISSUE TITLE
Is there way to get the value of --name provided in spark-submit into the spline-spark-agent's payload

### ISSUE THREAD

**Issue by dhineshns** [AbsaOSS/spline-spark-agent#261]
I took look at the payload that spline-spark-agent sends to the server and it looks like it doesn't have the job name. Is there a way to get the job name into the payload?

**Comment by cerveada** [comment]
You can implement a filter and add anything you need into payload. 
Take a look at: https://github.com/AbsaOSS/spline-spark-agent#filters

**Comment by wajda** [comment]
Are you running Spark in a cluster mode?
Actually, the agent does capture the app name via `sparkContext.appName` (which in turn takes value from `spark.app.name` property), and it stores it in the `executionPlan.extraInfo.appName` (and also in `executionPlan.name` since ver. 0.6.0)

If you don't see it being captured then it could probably be a cluster mode specific behavior. For example, see this - https://stackoverflow.com/a/42883306/96766

If that's the case then we need to take a closer look and see what can we do about it.

**Comment by mfrictionless** [comment]
> You can implement a filter and add anything you need into payload.
> Take a look at: https://github.com/AbsaOSS/spline-spark-agent#filters

@cerveada,

Would it be possible for you to post a simple example of a post processing filter.  I would really like to get some extra info out of Databricks and attach it to the Spline outputs and I'm having some trouble getting started with the implementation.

Thanks,

Michael

**Comment by cerveada** [comment]
Sure, for example take a look at [DataSourcePasswordReplacingFilter.scala](https://github.com/AbsaOSS/spline-spark-agent/blob/release/0.6/core/src/main/scala/za/co/absa/spline/harvester/postprocessing/DataSourcePasswordReplacingFilter.scala) It's a ready to use filter implementation provided by us.

Also take a look at [spline.default.properties](https://github.com/AbsaOSS/spline-spark-agent/blob/release/0.6/core/src/main/resources/spline.default.properties) to see how spline is configured to use filters.

**Comment by wajda** [comment]
Spline agent extension example project - https://github.com/AbsaOSS/spline-getting-started/tree/main/spark-agent-extension-example
