### ISSUE TITLE
Incomplete tracking of lineage for passthrough columns

### ISSUE THREAD

**Issue by afgaron** [AbsaOSS/spline-spark-agent#486]
If a query selects a column from one table and writes it to another without performing any operations on that column, then the execution plan doesn't differentiate between the old column and the new column and assigns both the same attribute id. For example,

```
create table B as (
    select val from A
)
```

will only have a single attribute with id `attr-0` and name `val`, rather than having two attributes for `A.val` and `B.val`. Even something like 

```
create table B as (
    select val as val from A
)
```

will cause the execution plan to have two attributes with different ids, both named `val`, for `A.val` and `B.val`. In more complicated queries, this makes lineage ambiguous (does the operation referring to `attr-0` mean `A.val` or `B.val`?), and it erases the lineage for the passthrough column itself (`B.val` depends on `A.val`, but they have the same id, so there aren't any operations "connecting" them).

I don't know if this is spline agent bug or a limitation of spark, but our desired behavior is that every input and output attribute would have a _unique_ id, even when the column has the same name, so that we can trace passthrough columns as well as modified columns.

**Comment by cerveada** [comment]
I think in this case Spark simple consider them both the same column and righty so. There is no difference between them.
We don't want to change the attribute names, since the user can name them as they wish and we should not change that.

- If the names are important for you I would suggest using `as` to name the columns and you can later identify them by that name.

- if you really want to change the spline lineage you can write your own [Post Processing Filter](https://github.com/AbsaOSS/spline-spark-agent#post-processing-filters), but I think it's overkill for this case.

**Comment by wajda** [comment]
If I understand you correctly then it is by Spark design. When you do `select val from A` Spark represents it as a `Projection` operation that emits the very same attribute `val` from the table `A`. So you have a single attribute and no place for ambiguity.

In your second example, when you do `select val as val from A` the `Projection` operation emits a new attribute with other ID but the same name `val` (as you instructed). The second attribute is still just a pointer to the first one through a named attribute reference expression. The only ambiguity I can see here is in colliding attribute names which might pop up on the UI, but I would say it's rather related to how UI displays stuff, as from the perspective of captured metadata all relevant relations are in place. So you can actually tell what is what by examining the stored execution plan.
Correct me if I'm missing something.
