### ISSUE TITLE
spline agent version required  for spark 3.4

### ISSUE THREAD

**Issue by SATPARDE** [AbsaOSS/spline-spark-agent#734]
we want spline agent version required  for spark 3.4.

is it already available or it is yet to release?

If it is not released yet then may i know possible timeline to get is released.

We are eagerly waiting for response from you.

**Comment by wajda** [comment]
Closing as a duplicate for #705.

@SATPARDE there is no timeline, but the demand is raising, so we'll likely start working on it very soon.

**Comment by Neelotpaul** [comment]
hi @wajda can you inform when spline agent bundle for spark 3.4 demand is completed. It's impacting our production jobs

**Comment by wajda** [comment]
I will. But the work hasn't been started yet. I estimate Sep-Oct. The team is currently occupied with other things.

Pull-request are always welcome. If you can adapt the agent so that it works at least on Spark 3.4 alone, even if your change breaks any other Spark versions, please don't hesitate to share a PR with us. It will cirtainly speed up the official release.

**Comment by SATPARDE** [comment]
we want spline agent version required for spark 3.4.

I saw in above messages estimate from your side was sep-oct.
So is it available now? if not then what is the new estimate.
We are facing  some issue with old version ,so wanted to use new version of spark and its imp issue.

So Can you please provide details on this?it would be helpfull

**Comment by wajda** [comment]
@SATPARDE, this issue is closed as a duplicate. Please refer to the issue #705
