### ISSUE TITLE
Ability to replace pattern in application name for lineage

### ISSUE THREAD

**Issue by DaimonPl** [AbsaOSS/spline-spark-agent#81]
In our setup we have jobs with generated names - usually dates, for example `my-app-2020-05-01`

For lineage purposes it would be better to report it as `my-app-YYYY-MM-DD`

@wajda have you thought about such feature? Do you think it would be useful for others? I could try to add implementation for it but let me know first

**Comment by wajda** [comment]
Do you mean dynamically replacing the app name specifically for lineage purposes, based on a user pattern?

**Comment by DaimonPl** [comment]
Exactly, example:

real app name: `my-app-2020-05-01`
replace pattern config: `\d{4}-\d{2}-\d{2}`
replace value config: `YYYY-MM-DD`
lineage app name: `my-app-YYYY-MM-DD`

of course config would be optional

**Comment by wajda** [comment]
It's possible in the Spline agent 0.6. See https://github.com/AbsaOSS/spline-spark-agent/issues/35#issuecomment-629865953

The App name is reported as an extra property of the execution plan:
```json
{
  ...
  "extraInfo": {
    "appName": "foo bar",
    ...
  }
}
```

You can extend `UserExtraMetadataProvider` to override this key as you wish, and register it in the config as `spline.user_extra_meta_provider.className=...`

**Comment by DaimonPl** [comment]
Ok, looks I'll need to wait for 0.6 then :)

**Comment by wajda** [comment]
Or I'll need to backport it to 0.5 :)
We've got plenty of work for 0.6, it won't come out anytime soon.

**Comment by wajda** [comment]
there - 5984af8f23606f4ce80e686b9af15991b36113c8

**Comment by wajda** [comment]
Closing in favor of #35

**Comment by DaimonPl** [comment]
@wajda one more question, because there are multiple overrides

```
override def forExecEvent(event: ExecutionEvent, ctx: HarvestingContext): Map[String, Any]
  override def forExecPlan(plan: ExecutionPlan, ctx: HarvestingContext): Map[String, Any] 
  override def forOperation(op: ReadOperation, ctx: HarvestingContext): Map[String, Any] 
  override def forOperation(op: WriteOperation, ctx: HarvestingContext): Map[String, Any] 
  override def forOperation(op: DataOperation, ctx: HarvestingContext): Map[String, Any] 
```

following setting should be overwritten in each of them?

```
{
  "extraInfo": {
    "appName": "foo bar",
  }
}
```

**Comment by wajda** [comment]
No-no, only the one that you need. It's like in a _Visitor_ pattern. Those methods are called for extra info to be included in respected elements of the lineage data structure. In your case you need to implement `forExecPlan()` because you want to alter an execution plan extra info.

**Comment by DaimonPl** [comment]
@wajda one more question. Can it be somehow used to modify datasource URI?

For example when writing data i have following URI:

hdfs://xyz/tables/my_table/dt=2020-05-15

but when reading spline resolves

hdfs://xyz/tables/my_table/

is there a way to use extra metadata to intercept write uri and modify it on the fly ?

**Comment by wajda** [comment]
Not with this API, but you can do it in a custom dispatcher. Similar to this one -  https://github.com/AbsaOSS/spline-spark-agent/issues/35#issuecomment-597789962

**Comment by DaimonPl** [comment]
Ok git it working :)

One more question, what's difference between exec plan and exec event? I'd like to filter out certain plans but exec events contain only ids

**Comment by wajda** [comment]
Currently, for the Spark agent the difference is only semantic, because for every job run there will be one exec plan and one exec event created. But from the perspective of Producer API the difference is fundamental:
- _Execution Plan_ describes static aspects of the data transformation - **where** we read from, **how** we transform the data, **where** we write the result to. In other words it represents the formulas, or job templates if you will.
- _Execution Event_ on the other hand represents dynamic aspects of things - **which** _Execution Plan_ has executed and **when**, what was the **result** of the execution (success or failure, and what was an error if such), and perhaps some metrics.

If we could reliably compare execution plans and check for their semantic equality, one execution plan could be linked to many execution events (think about repeated jobs for instance)
In the future, we plan to expand this model to track streaming jobs.
